version: '3.7'

services:
  celery_beat_app:
    build:
      context: .
      dockerfile: compose/.local/Dockerfile
    image: image_celery_beat_local
    container_name: celery_beat_local
    volumes:
      - .:/app:z
      - ./celery_service/task_json:/celery_service/task_json
      - ./celery_beat_schedule:/celery_beat_schedule
    env_file:
      - .envs/.local
      - .envs/.postgres
    depends_on:
      - redis
    networks:
      - gropoz-network
    command: /celery_start/beat/start

  celery_worker_app:
    build:
      context: .
      dockerfile: compose/.local/Dockerfile
    image: image_celery_worker_local
    container_name: celery_worker_local
    volumes:
      - .:/app:z
      - ./celery_service/task_json:/celery_service/task_json
      - ./celery_beat_schedule:/celery_beat_schedule
    env_file:
      - .envs/.local
      - .envs/.postgres
    depends_on:
      - redis
    networks:
      - gropoz-network
    command: /celery_start/worker/start

  celery_flower_app:
    build:
      context: .
      dockerfile: compose/.local/Dockerfile
    image: image_celery_flower_local
    container_name: celery_flower_local
    volumes:
      - .:/app:z
      - ./celery_service/task_json:/celery_service/task_json
      - ./celery_beat_schedule:/celery_beat_schedule
    env_file:
      - .envs/.local
      - .envs/.postgres
    depends_on:
      - redis
    ports:
      - "5555:5555"
    networks:
      - gropoz-network
    command: /celery_start/flower/start

  redis:
    image: redis:6-alpine
    networks:
      - gropoz-network

networks:
    gropoz-network:
      external: true