version: '3'

services:
  celery_beat_app:
    build:
      context: .
      dockerfile: compose/.production/Dockerfile
    image: image_celery_beat_production
    volumes:
      - .:/app:z
    env_file:
      - .envs/.local
    depends_on:
      - redis
    command: /start

  redis:
    image: redis:6
