#!/bin/bash

set -o errexit
set -o nounset
rm -f './celerybeat.pid'


PATH_BEAT_SCHEDULE=celery_beat_schedule

celery -A celery_service beat -l INFO --schedule $PATH_BEAT_SCHEDULE/celerybeat-schedule.db